modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Creators-of-Create/Create/issues"
license = "MIT"

[[mods]]
modId = "create_update6_backport"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version = "1.0.0"
displayName = "Create update 6 backport"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create-update-6-backport"
logoFile = "icon.png"
#credits=""
authors = "CreateModFan12"
description = '''
a backport of all create update 6 features
'''

[[dependencies.create]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.create]]
modId = "jei"
mandatory = false
versionRange = "[15.19.0,)"
ordering = "NONE"
side = "CLIENT"
